export default imageStirngs = {
  OnboardingSwiperBackground: require('../../assets/images/onboarding/GradientBackground.png'),
  OnboardingScreen1Image: require('../../assets/images/onboarding/Onboarding1.png'),
  OnboardingScreen2Image: require('../../assets/images/onboarding/Onboarding2.png'),
  LoginScreenBackground: require('../../assets/images/LoginBackground.png'),
  SignupScreenBackground: require('../../assets/images/SignupBackground.png'),
  adSlider: [
    require('../../assets/demo.png'),
    require('../../assets/homepageAdSliderImages/banner.png'),
    require('../../assets/homepageAdSliderImages/banner.png'),
  ],
  iconImages: {
    notificationOutline: require('../../assets/buttonIcons/Notification-outline.png'),
    notification: require('../../assets/buttonIcons/Notification.png'),
    homeSelected: require('../../assets/bottomTabIcons/HomeSelected.png'),
    home: require('../../assets/bottomTabIcons/Home.png'),
    categoriesSelected: require('../../assets/bottomTabIcons/CategoriesSelected.png'),
    categories: require('../../assets/bottomTabIcons/Categories.png'),
    cart: require('../../assets/bottomTabIcons/Cart.png'),
    favoritesSelected: require('../../assets/bottomTabIcons/HeartSelected.png'),
    favorites: require('../../assets/bottomTabIcons/Heart.png'),
    userSelected: require('../../assets/bottomTabIcons/UserSelected.png'),
    user: require('../../assets/bottomTabIcons/User.png'),
  },
  categoriesImages: [
    {
      name: 'vegetables',
      image: require('../../assets/categoryIcons/Cabbage.png'),
    },
    {name: 'chicken', image: require('../../assets/categoryIcons/Chicken.png')},
    {name: 'freshFish', image: require('../../assets/categoryIcons/Fish.png')},
    {name: 'dairy', image: require('../../assets/categoryIcons/Cake.png')},
    {name: 'fruits', image: require('../../assets/categoryIcons/Lemon.png')},
  ],
  productImages: [
    {name: 'apple', image: require('../../assets/productImages/Apple.png')},
    {
      name: 'bananasBig',
      image: require('../../assets/productImages/BananasBig.png'),
    },
    {name: 'brocoli', image: require('../../assets/productImages/Brocoli.png')},
    {name: 'cake', image: require('../../assets/productImages/Cake.png')},
    {name: 'coconut', image: require('../../assets/productImages/Coconut.png')},
    {
      name: 'frenchFries',
      image: require('../../assets/productImages/FrenchFries.png'),
    },
    {name: 'kiwi', image: require('../../assets/productImages/Kiwi.png')},
    {name: 'lemon', image: require('../../assets/productImages/Lemon.png')},
    {name: 'meat', image: require('../../assets/productImages/Meat.png')},
    {name: 'orange', image: require('../../assets/productImages/Orange.png')},
    {name: 'pumpkin', image: require('../../assets/productImages/Pumpkin.png')},
    {name: 'salad', image: require('../../assets/productImages/Salad.png')},
    {
      name: 'strawberies',
      image: require('../../assets/productImages/Strawberies.png'),
    },
    {name: 'tomato', image: require('../../assets/productImages/Tomato.png')},
  ],
  discount: require('../../assets/discount.png'),
  cartIcon: require('../../assets/cartIcon.png'),
  deliveryTruck: require('../../assets/truck.png'),
  coupon: require('../../assets/coupon.png'),
};
