import ImageStrings from './strings/ImageStrings';

export const data = [
  {
    categoryName: 'Fruits',
    items: [
      {
        productName: 'Banana',
        title: 'Organic banana',
        rating: 4.5,
        ratings: 97,
        price: 115,
        maxDiscount: 150,
        discountPercentage: 50,
        images: [
          ImageStrings.productImages.bananasBig,
          ImageStrings.productImages.bananasBig,
        ],
      },
      {
        productName: 'Strawberry',
        title: 'Fresh Strawberry',
        rating: 4.3,
        ratings: 15,
        price: 39,
        maxDiscount: 150,
        discountPercentage: 50,
        images: [
          ImageStrings.productImages.strawberies,
          ImageStrings.productImages.strawberies,
        ],
      },
      {
        productName: 'Apple',
        title: 'Red Apple',
        rating: 4.3,
        ratings: 45,
        price: 75,
        maxDiscount: 150,
        discountPercentage: 50,
        images: [
          ImageStrings.productImages.apple,
          ImageStrings.productImages.apple,
        ],
      },
      {
        productName: 'Orange',
        title: 'Fresh Orange',
        rating: 4.3,
        ratings: 45,
        price: 150,
        discountPercentage: 50,
        maxDiscount: 150,
        images: [
          ImageStrings.productImages.orange,
          ImageStrings.productImages.orange,
        ],
      },
      {
        productName: 'Coconut',
        title: 'Fresh Coconut',
        rating: 4.2,
        ratings: 99,
        price: 100,
        discountPercentage: 50,
        maxDiscount: 150,
        images: [
          ImageStrings.productImages.coconut,
          ImageStrings.productImages.coconut,
        ],
      },
      {
        productName: 'Lemon',
        title: 'Fresh Lemon',
        rating: 4.2,
        ratings: 99,
        price: 75,
        discountPercentage: 50,
        maxDiscount: 150,
        images: [
          ImageStrings.productImages.lemon,
          ImageStrings.productImages.lemon,
        ],
      },
      {
        productName: 'Kiwi Fruit',
        title: 'Kiwi Fruit',
        rating: 4.2,
        ratings: 99,
        price: 75,
        discountPercentage: 50,
        maxDiscount: 150,
        images: [
          ImageStrings.productImages.kiwi,
          ImageStrings.productImages.kiwi,
        ],
      },
    ],
    total: 1126,
    image: ImageStrings.categoriesImages.fruits,
  },
  {
    categoryName: 'Chicken',
    items: [
      {
        productName: 'Meat',
        title: 'Meat',
        rating: 4.2,
        ratings: 99,
        price: 2,
        discountPercentage: 50,
        maxDiscount: 150,
        images: [
          ImageStrings.productImages.meat,
          ImageStrings.productImages.meat,
        ],
      },
      {
        productName: 'Banana',
        title: 'Organic banana',
        rating: 4.5,
        ratings: 97,
        price: 115,
        maxDiscount: 150,
        discountPercentage: 50,
        images: [
          ImageStrings.productImages.bananasBig,
          ImageStrings.productImages.bananasBig,
        ],
      },
      {
        productName: 'Strawberry',
        title: 'Fresh Strawberry',
        rating: 4.3,
        ratings: 15,
        price: 39,
        maxDiscount: 150,
        discountPercentage: 50,
        images: [
          ImageStrings.productImages.strawberies,
          ImageStrings.productImages.strawberies,
        ],
      },
      {
        productName: 'Apple',
        title: 'Red Apple',
        rating: 4.3,
        ratings: 45,
        price: 75,
        maxDiscount: 150,
        discountPercentage: 50,
        images: [
          ImageStrings.productImages.apple,
          ImageStrings.productImages.apple,
        ],
      },
      {
        productName: 'Orange',
        title: 'Fresh Orange',
        rating: 4.3,
        ratings: 45,
        price: 150,
        discountPercentage: 50,
        maxDiscount: 150,
        images: [
          ImageStrings.productImages.orange,
          ImageStrings.productImages.orange,
        ],
      },
    ],
    total: 1126,
    image: ImageStrings.categoriesImages.chicken,
  },
  {
    categoryName: 'Fresh Fish',
    items: [],
    total: 1126,
    image: ImageStrings.categoriesImages.freshFish,
  },
  {
    categoryName: 'Dairy',
    items: [
      {
        productName: 'Cake',
        title: 'Cool Cake',
        rating: 4.2,
        ratings: 99,
        price: 2,
        discountPercentage: 50,
        maxDiscount: 150,
        images: [
          ImageStrings.productImages.cake,
          ImageStrings.productImages.cake,
        ],
      },
      {
        productName: 'Frech Fries',
        title: 'Frech Fries',
        rating: 4.2,
        ratings: 99,
        price: 2,
        discountPercentage: 50,
        maxDiscount: 150,
        images: [
          ImageStrings.productImages.cake,
          ImageStrings.productImages.cake,
        ],
      },
    ],
    total: 1126,
    image: ImageStrings.categoriesImages.vegetables,
  },
  {
    categoryName: 'Vegetables',
    items: [
      {
        productName: 'Brocoli',
        title: 'Brocoli',
        rating: 4.2,
        ratings: 99,
        price: 2,
        discountPercentage: 50,
        maxDiscount: 150,
        images: [
          ImageStrings.productImages.brocoli,
          ImageStrings.productImages.brocoli,
        ],
      },
      {
        productName: 'Salad',
        title: 'Fresh Salad',
        rating: 4.2,
        ratings: 99,
        price: 2,
        discountPercentage: 50,
        maxDiscount: 150,
        images: [
          ImageStrings.productImages.salad,
          ImageStrings.productImages.salad,
        ],
      },
      {
        productName: 'Banana',
        title: 'Organic banana',
        rating: 4.5,
        ratings: 97,
        price: 115,
        maxDiscount: 150,
        discountPercentage: 50,
        images: [
          ImageStrings.productImages.bananasBig,
          ImageStrings.productImages.bananasBig,
        ],
      },
      {
        productName: 'Strawberry',
        title: 'Fresh Strawberry',
        rating: 4.3,
        ratings: 15,
        price: 39,
        maxDiscount: 150,
        discountPercentage: 50,
        images: [
          ImageStrings.productImages.strawberies,
          ImageStrings.productImages.strawberies,
        ],
      },
      {
        productName: 'Apple',
        title: 'Red Apple',
        rating: 4.3,
        ratings: 45,
        price: 75,
        maxDiscount: 150,
        discountPercentage: 50,
        images: [
          ImageStrings.productImages.apple,
          ImageStrings.productImages.apple,
        ],
      },
      {
        productName: 'Orange',
        title: 'Fresh Orange',
        rating: 4.3,
        ratings: 45,
        price: 150,
        discountPercentage: 50,
        maxDiscount: 150,
        images: [
          ImageStrings.productImages.orange,
          ImageStrings.productImages.orange,
        ],
      },
    ],
    total: 1126,
    image: ImageStrings.categoriesImages.vegetables,
  },
];
